name: Run Unit Tests on Repo

on: 
  pull_request:  

jobs:
  run-unit-tests: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: npm install and run tests
      run: |
        npm i
        npm run test